### ISSUE TITLE
如何禁用掉homekit里面的制热模式，只保留制冷模式？

### ISSUE THREAD

**Issue by howedeng123** [mypal/ha-dsair#61]
目前的情况：
1、金制空气app里面有4种模式：制冷、制热、除湿、送风
2、home assistant里面有3种模式：制冷、除湿、送风
3、homekit里面只有2种模式：制冷、制热

问题：由于身处广东，没有制热需求，为了减少家人误操作，有没有什么方法可以在homekit只保留制冷模式？

**Comment by Necroneco** [comment]
方法应该有很多，你可以试试 HA 的 customize，直接重定义这些 climate 的 `hvac_modes`

参考文档：
https://www.home-assistant.io/docs/configuration/customizing-devices/#manual-customization

参考示例：
```yaml
homeassistant:
  customize:
    climate.ke_ting:
      hvac_modes:
        - cool
        - dry
        - fan_only
        - 'off'
```
